spring:
  ms:
    application:
      name: companies-crud
    datasource:
      username: talis
      hikari:
        maximum-pool-size: 5
        connection-timeout: 20000
      url: jdbc:postgresql://localhost:5434/companies-prod
      password: dev123qweProd
